addSbtPlugin("org.wartremover"	% "sbt-wartremover"		% "2.4.3")
addSbtPlugin("com.eed3si9n"		% "sbt-buildinfo"		% "0.9.0")
addSbtPlugin("de.djini" 		% "xsbt-osxapp"			% "2.6.0")
addSbtPlugin("de.djini" 		% "xsbt-capsule"		% "2.4.0")
addSbtPlugin("de.djini" 		% "xsbt-scriptstart"	% "2.4.0")
