addSbtPlugin("org.wartremover"	% "sbt-wartremover"		% "2.4.13")
addSbtPlugin("com.eed3si9n"		% "sbt-buildinfo"		% "0.10.0")
addSbtPlugin("de.djini" 		% "xsbt-osxapp"			% "2.7.0")
addSbtPlugin("de.djini"			% "xsbt-kapsel"			% "0.3.0")
addSbtPlugin("de.djini" 		% "xsbt-scriptstart"	% "2.5.0")
