addSbtPlugin("org.wartremover"	% "sbt-wartremover"		% "3.0.5")
addSbtPlugin("com.eed3si9n"		% "sbt-buildinfo"		% "0.11.0")
addSbtPlugin("de.djini" 		% "xsbt-osxapp"			% "2.8.0")
addSbtPlugin("de.djini"			% "xsbt-kapsel"			% "0.5.0")
addSbtPlugin("de.djini" 		% "xsbt-scriptstart"	% "2.6.0")
